[build]
  base = ""
  publish = "docs/output"
  command = "make build-docs"

[[redirects]]
  from = "/"
  to = "/master/"
  force = true

[[redirects]]
  from = "/wrong-url"
  to = "/master/"
  force = true